/**
 * Historical rate dataset loader: monthly month-end observations,
 * Oct 2008 - Mar 2026, from `public/rate_history_2008-10_2026-03.json`
 * (generated by `research/convert_rate_history.py` from the owner-curated
 * workbook, trimmed by filter to the 2026-03-31 snapshot date; single copy
 * of truth, research scripts read the same file).
 *
 * Series: Fed Target, EFFR, overnight SOFR, SOFR term curve (17 tenors,
 * 1M-360M), FHLB advance curve (17 tenors). Rates are DECIMAL per annum,
 * matching `CurveQuote.rate`. Provenance: SOFR publication began Apr 2018;
 * earlier SOFR tenor values are an OIS/EFFR-based proxy splice (metadata
 * carries the note for UI labeling).
 *
 * Trailing-MA convention (tractor pillars): the window is INCLUSIVE of the
 * as-of month, `mean(values[i-k+1 .. i])`, matching
 * `research/rp_tractor_verify.py` (`OVN[-k:].mean()`). This deliberately
 * differs from the NMD incentive-spread window in `instruments/nmd.ts`,
 * which averages the k months STRICTLY PRIOR to the current month.
 * Before the first complete window the MA is NaN, never a silently
 * truncated average; consumers drop or gap NaN entries.
 */

export interface RateHistoryProvenance {
  readonly sourceWorkbook: string;
  readonly sofrNote: string;
  readonly fhlbNote: string;
}

export interface RateHistory {
  /** ISO "YYYY-MM" month labels, index-aligned with every series. */
  readonly months: ReadonlyArray<string>;
  readonly tenorsMonths: ReadonlyArray<number>;
  readonly fedTarget: ReadonlyArray<number>;
  readonly effr: ReadonlyArray<number>;
  readonly sofrON: ReadonlyArray<number>;
  readonly provenance: RateHistoryProvenance;
  /** Index of an ISO "YYYY-MM" month, -1 if outside the dataset. */
  indexOfMonth(iso: string): number;
  /** SOFR term rate at a month, linear in tenor between nodes (clamped). */
  sofrTermRate(monthIdx: number, tenorMonths: number): number;
  fhlbTermRate(monthIdx: number, tenorMonths: number): number;
  /** Full monthly series for one tenor (interpolated if off-node). */
  sofrTermSeries(tenorMonths: number): number[];
  fhlbTermSeries(tenorMonths: number): number[];
  /**
   * Tractor pillar steady-state yield: trailing k-month MA of the k-month
   * SOFR tenor, inclusive of the as-of month. NaN before the first
   * complete window.
   */
  pillarYield(asOfIdx: number, kMonths: number): number;
}

/** First index with a complete inclusive k-month window. */
export function firstCompleteIndex(k: number): number {
  return k - 1;
}

/** Inclusive trailing MA at one index; NaN if the window is incomplete. */
export function trailingMA(values: ArrayLike<number>, asOfIdx: number, k: number): number {
  if (k <= 0 || asOfIdx < 0 || asOfIdx >= values.length) return NaN;
  if (asOfIdx < firstCompleteIndex(k)) return NaN;
  let sum = 0;
  for (let j = asOfIdx - k + 1; j <= asOfIdx; j++) sum += values[j];
  return sum / k;
}

/** Inclusive trailing MA over a whole series; NaN before the first complete window. */
export function trailingMASeries(values: ArrayLike<number>, k: number): number[] {
  const out = new Array<number>(values.length).fill(NaN);
  if (k <= 0) return out;
  let sum = 0;
  for (let i = 0; i < values.length; i++) {
    sum += values[i];
    if (i >= k) sum -= values[i - k];
    if (i >= k - 1) out[i] = sum / k;
  }
  return out;
}

interface RawTermBlock {
  tenors_months: number[];
  rates: number[][];
}

interface RawRateHistory {
  name: string;
  start_month: string;
  end_month: string;
  months: number;
  units: string;
  provenance: {
    source_workbook: string;
    sofr_note: string;
    fhlb_note: string;
  };
  fed_target: number[];
  effr: number[];
  sofr_on: number[];
  sofr_term: RawTermBlock;
  fhlb_term: RawTermBlock;
}

function isoMonthsFrom(startIso: string, count: number): string[] {
  const m = /^(\d{4})-(\d{2})$/.exec(startIso);
  if (!m) throw new Error(`rateHistory: bad start_month "${startIso}"`);
  let year = Number(m[1]);
  let month = Number(m[2]);
  const out: string[] = [];
  for (let i = 0; i < count; i++) {
    out.push(`${year.toString().padStart(4, "0")}-${month.toString().padStart(2, "0")}`);
    month += 1;
    if (month > 12) {
      month = 1;
      year += 1;
    }
  }
  return out;
}

function checkSeries(name: string, values: number[], expectedLen: number): void {
  if (values.length !== expectedLen) {
    throw new Error(`rateHistory: ${name} has ${values.length} entries, expected ${expectedLen}`);
  }
  for (let i = 0; i < values.length; i++) {
    if (!Number.isFinite(values[i])) {
      throw new Error(`rateHistory: ${name}[${i}] is not a finite number`);
    }
  }
}

function checkTermBlock(name: string, block: RawTermBlock, expectedLen: number): void {
  for (let i = 1; i < block.tenors_months.length; i++) {
    if (block.tenors_months[i] <= block.tenors_months[i - 1]) {
      throw new Error(`rateHistory: ${name} tenor axis not strictly increasing at index ${i}`);
    }
  }
  if (block.rates.length !== expectedLen) {
    throw new Error(`rateHistory: ${name} has ${block.rates.length} rows, expected ${expectedLen}`);
  }
  for (let i = 0; i < block.rates.length; i++) {
    checkSeries(`${name}.rates[${i}]`, block.rates[i], block.tenors_months.length);
  }
}

/** Linear interpolation in tenor months, clamped at the ends. */
function interpTenor(tenors: ReadonlyArray<number>, row: ReadonlyArray<number>, t: number): number {
  if (t <= tenors[0]) return row[0];
  const last = tenors.length - 1;
  if (t >= tenors[last]) return row[last];
  let i = 1;
  while (tenors[i] < t) i++;
  const w = (t - tenors[i - 1]) / (tenors[i] - tenors[i - 1]);
  return row[i - 1] + w * (row[i] - row[i - 1]);
}

export function parseRateHistory(raw: RawRateHistory): RateHistory {
  const n = raw.months;
  if (!Number.isInteger(n) || n <= 0) {
    throw new Error(`rateHistory: bad month count ${raw.months}`);
  }
  const months = isoMonthsFrom(raw.start_month, n);
  if (months[n - 1] !== raw.end_month) {
    throw new Error(
      `rateHistory: end_month ${raw.end_month} disagrees with start_month + ${n} months (${months[n - 1]})`,
    );
  }
  checkSeries("fed_target", raw.fed_target, n);
  checkSeries("effr", raw.effr, n);
  checkSeries("sofr_on", raw.sofr_on, n);
  checkTermBlock("sofr_term", raw.sofr_term, n);
  checkTermBlock("fhlb_term", raw.fhlb_term, n);
  if (raw.sofr_term.tenors_months.join() !== raw.fhlb_term.tenors_months.join()) {
    throw new Error("rateHistory: SOFR and FHLB tenor axes differ");
  }

  const tenors = raw.sofr_term.tenors_months;
  const monthIndex = new Map<string, number>(months.map((m, i) => [m, i]));
  const nodeIndex = new Map<number, number>(tenors.map((t, i) => [t, i]));

  const termRate = (block: RawTermBlock, monthIdx: number, tenorMonths: number): number => {
    if (monthIdx < 0 || monthIdx >= n) {
      throw new Error(`rateHistory: month index ${monthIdx} out of range 0..${n - 1}`);
    }
    const node = nodeIndex.get(tenorMonths);
    const row = block.rates[monthIdx];
    return node !== undefined ? row[node] : interpTenor(tenors, row, tenorMonths);
  };

  const termSeries = (block: RawTermBlock, tenorMonths: number): number[] => {
    const out = new Array<number>(n);
    for (let i = 0; i < n; i++) out[i] = termRate(block, i, tenorMonths);
    return out;
  };

  return {
    months,
    tenorsMonths: tenors,
    fedTarget: raw.fed_target,
    effr: raw.effr,
    sofrON: raw.sofr_on,
    provenance: {
      sourceWorkbook: raw.provenance.source_workbook,
      sofrNote: raw.provenance.sofr_note,
      fhlbNote: raw.provenance.fhlb_note,
    },
    indexOfMonth: (iso) => monthIndex.get(iso) ?? -1,
    sofrTermRate: (m, t) => termRate(raw.sofr_term, m, t),
    fhlbTermRate: (m, t) => termRate(raw.fhlb_term, m, t),
    sofrTermSeries: (t) => termSeries(raw.sofr_term, t),
    fhlbTermSeries: (t) => termSeries(raw.fhlb_term, t),
    pillarYield: (asOfIdx, kMonths) =>
      trailingMA(termSeries(raw.sofr_term, kMonths), asOfIdx, kMonths),
  };
}

/** Load the rate history from a JSON URL (browser) or path (Node tests). */
export async function loadRateHistory(source: string | URL): Promise<RateHistory> {
  if (typeof window !== "undefined") {
    const res = await fetch(source);
    if (!res.ok) {
      throw new Error(`Failed to load rate history: ${res.status} ${res.statusText}`);
    }
    return parseRateHistory((await res.json()) as RawRateHistory);
  }
  // Node fallback for tests: dynamic import of fs.
  const { readFile } = await import("node:fs/promises");
  const text = await readFile(source as string, "utf-8");
  return parseRateHistory(JSON.parse(text) as RawRateHistory);
}

export const RATE_HISTORY_FILENAME = "rate_history_2008-10_2026-03.json";

let cached: Promise<RateHistory> | null = null;

/**
 * Singleton loader for the bundled dataset (browser). First caller triggers
 * the fetch; later tabs (Replicating Portfolio) reuse the same promise.
 */
export function loadRateHistoryOnce(baseUrl: string): Promise<RateHistory> {
  if (!cached) {
    cached = loadRateHistory(`${baseUrl}${RATE_HISTORY_FILENAME}`).catch((err) => {
      cached = null; // allow retry after a failed fetch
      throw err;
    });
  }
  return cached;
}
